# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 https://www.jelani.dev
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jelani Woods
  url:               https://www.jelani.dev
  email:             jelani@firstdraft.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-slate
